[advisories]
ignore = [
    # All lockfiles
    # Cargo.lock
    # Cargo-maximum.lock
    # Cargo-recent.lock
    # Cargo-minimal.lock
    "RUSTSEC-2026-0009", # unpatchable: time@v0.3.46 requires MSRV >= 1.86.0
]
