[advisories]
ignore = [
    "RUSTSEC-2026-0049", # blame: floresta-wire
    "RUSTSEC-2026-0097", # blame: rand 0.8.5
    "RUSTSEC-2026-0098", # blame: floresta-wire
    "RUSTSEC-2026-0099", # blame: floresta-wire
    "RUSTSEC-2026-0104", # blame: floresta-wire
]
