name: Commits

on:
    push:
      branches: [ master ]
    pull_request:

permissions: {}
env:
    CARGO_TERM_COLOR: always

jobs:
    signatures:
        name: Check PGP Signatures
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - name: Assert Commits are Signed
              run: bash contrib/check-signatures.sh

    conventional-commits:
        name: Assert Conventinal Commits
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - name: Check Commit Messages
              uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2
              with:
                  allowed-commit-types: "feat,fix,doc,refactor,test,ci,chore,fuzz,bench"
